apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-pipelines/tektoncd-hub?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" &&
      ("upstream/***".pathChanged() || "openshift/***".pathChanged() ||
      ".tekton/hub-ui-pull-request.yaml".pathChanged() ||
      ".tekton/hub-ui-push.yaml".pathChanged() ||
      ".tekton/docker-build.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tektoncd-hub-main
    appstudio.openshift.io/component: tektoncd-hub-main-hub-ui
    pipelines.appstudio.openshift.io/type: build
  name: tektoncd-hub-main-hub-ui-on-push
  namespace: tekton-ecosystem-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-ui:{{revision}}
  - name: dockerfile
    value: openshift/dockerfiles/hub-ui.Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: |
      {"type": "npm", "path": "upstream/ui"}
  pipelineRef:
    name: docker-build
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
